[package]
name = "cli-arg-parser-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: replace with thiserror
anyhow = "1"

[features]
default = []
utf = []
ascii = []